-- Envers 修订历史表（仅白名单非敏感字段的实体参与审计：users / devices）。
--
-- 与操作审计（audit_events）职责不同：这里只记录低频账户/设备状态字段的修订，用于追溯；
-- 邮箱密文、SRP 材料、密钥封装、恢复材料、条目密文一律不进入修订表。
--
-- 说明：Hibernate Envers 7 依赖 schema 存在（ddl-auto=validate 不会自动建 _AUD 表）。
-- 表结构与自定义 RevisionEntity（VaultOneRevisionEntity）/ @Audited 字段一一对应。

-- revinfo 使用独立 long 主键（IDENTITY），并承载可信审计上下文列（账户/设备/请求）。
-- rev 是独立 long，不混协议 cursor/vk_gen；revtstmp 为 UTC epoch 毫秒。
CREATE TABLE revinfo (
  rev             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revtstmp        BIGINT NOT NULL,
  user_id         TEXT NOT NULL,
  actor_device_id TEXT,
  request_id      TEXT NOT NULL
);
CREATE INDEX idx_revinfo_user ON revinfo(user_id);

-- users 审计：仅 vk_gen / session_epoch / updated_at 参与（其余列的 @NotAudited 不进入本表）。
CREATE TABLE users_aud (
  id            TEXT NOT NULL,
  rev           BIGINT NOT NULL REFERENCES revinfo(rev),
  revtype       SMALLINT NOT NULL,
  vk_gen        BIGINT,
  session_epoch BIGINT,
  updated_at    TEXT,
  PRIMARY KEY (id, rev)
);

-- devices 审计：批准/撤销状态字段（name/platform/last_seen_at/epoch 为 @NotAudited，不进入本表）。
CREATE TABLE devices_aud (
  user_id     TEXT NOT NULL,
  id          TEXT NOT NULL,
  rev         BIGINT NOT NULL REFERENCES revinfo(rev),
  revtype     SMALLINT NOT NULL,
  approved_at TEXT,
  approved_by TEXT,
  revoked_at  TEXT,
  PRIMARY KEY (user_id, id, rev)
);

CREATE INDEX idx_users_aud_rev ON users_aud(rev);
CREATE INDEX idx_devices_aud_rev ON devices_aud(rev);

-- RLS：修订表同样受账户范围约束（users_aud 以 id，devices_aud 以 user_id，revinfo 以 user_id）。
-- Envers 写入发生在应用事务内、账户上下文已设置；无上下文或其他账户均不可见/不可写。
ALTER TABLE users_aud   ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_aud   FORCE  ROW LEVEL SECURITY;
ALTER TABLE devices_aud ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices_aud FORCE  ROW LEVEL SECURITY;
ALTER TABLE revinfo     ENABLE ROW LEVEL SECURITY;
ALTER TABLE revinfo     FORCE  ROW LEVEL SECURITY;

CREATE POLICY users_aud_account_isolation ON public.users_aud
  USING (id = vaultone_current_account())
  WITH CHECK (id = vaultone_current_account());

CREATE POLICY devices_aud_account_isolation ON public.devices_aud
  USING (user_id = vaultone_current_account())
  WITH CHECK (user_id = vaultone_current_account());

CREATE POLICY revinfo_account_isolation ON public.revinfo
  USING (user_id = vaultone_current_account())
  WITH CHECK (user_id = vaultone_current_account());

-- 最小权限：Envers 追加写入（INSERT）与查询（SELECT）；账户清理删除（DELETE）。修订行不可变，不授予 UPDATE。
GRANT SELECT, INSERT, DELETE ON users_aud, devices_aud, revinfo TO "${runtime_role}";
GRANT USAGE, SELECT ON SEQUENCE revinfo_rev_seq TO "${runtime_role}";
