package app.vaultone.server.audit.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.envers.RevisionEntity;
import org.hibernate.envers.RevisionNumber;
import org.hibernate.envers.RevisionTimestamp;

/**
 * Envers 自定义修订实体，匹配 SQL 侧 {@code revinfo}： {@code rev BIGINT GENERATED BY DEFAULT AS IDENTITY,
 * revtstmp BIGINT, user_id TEXT NOT NULL, actor_device_id TEXT NULL, request_id TEXT NOT NULL}。
 *
 * <p>{@code rev} 为独立 long；{@code revtstmp} 为 UTC epoch 毫秒；与协议 cursor / vk_gen 无关。 账户/actor/request
 * 字段由 {@link VaultOneRevisionListener} 从可信上下文填充。
 */
@Entity
@Table(name = "revinfo")
@RevisionEntity(VaultOneRevisionListener.class)
public class VaultOneRevisionEntity {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @RevisionNumber
  @Column(name = "rev")
  private Long rev;

  @RevisionTimestamp
  @Column(name = "revtstmp", nullable = false)
  private long revtstmp;

  @Column(name = "user_id", nullable = false)
  private String userId;

  @Column(name = "actor_device_id")
  private String actorDeviceId;

  @Column(name = "request_id", nullable = false)
  private String requestId;

  public Long getRev() {
    return rev;
  }

  public long getRevtstmp() {
    return revtstmp;
  }

  public String getUserId() {
    return userId;
  }

  public String getActorDeviceId() {
    return actorDeviceId;
  }

  public String getRequestId() {
    return requestId;
  }

  void setUserId(String userId) {
    this.userId = userId;
  }

  void setActorDeviceId(String actorDeviceId) {
    this.actorDeviceId = actorDeviceId;
  }

  void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  @Override
  public String toString() {
    return "VaultOneRevisionEntity[rev=" + rev + "]";
  }
}
