// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/clipboard.dart';
import 'api/logging.dart';
import 'api/sync.dart';
import 'api/tools.dart';
import 'api/vault.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountInfo dco_decode_account_info(dynamic raw);

  @protected
  AuditEventDto dco_decode_audit_event_dto(dynamic raw);

  @protected
  AuditFindingDto dco_decode_audit_finding_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RemoteStatusDto dco_decode_box_autoadd_remote_status_dto(dynamic raw);

  @protected
  TotpSpec dco_decode_box_autoadd_totp_spec(dynamic raw);

  @protected
  BreachResult dco_decode_breach_result(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  DeviceDto dco_decode_device_dto(dynamic raw);

  @protected
  EnrollmentDto dco_decode_enrollment_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Generated dco_decode_generated(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AuditEventDto> dco_decode_list_audit_event_dto(dynamic raw);

  @protected
  List<AuditFindingDto> dco_decode_list_audit_finding_dto(dynamic raw);

  @protected
  List<BreachResult> dco_decode_list_breach_result(dynamic raw);

  @protected
  List<DeviceDto> dco_decode_list_device_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RemoteStatusDto? dco_decode_opt_box_autoadd_remote_status_dto(dynamic raw);

  @protected
  ParsedTotp dco_decode_parsed_totp(dynamic raw);

  @protected
  RemoteStatusDto dco_decode_remote_status_dto(dynamic raw);

  @protected
  StrengthDto dco_decode_strength_dto(dynamic raw);

  @protected
  SyncReportDto dco_decode_sync_report_dto(dynamic raw);

  @protected
  TotpCodeDto dco_decode_totp_code_dto(dynamic raw);

  @protected
  TotpSpec dco_decode_totp_spec(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer);

  @protected
  AuditEventDto sse_decode_audit_event_dto(SseDeserializer deserializer);

  @protected
  AuditFindingDto sse_decode_audit_finding_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RemoteStatusDto sse_decode_box_autoadd_remote_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  TotpSpec sse_decode_box_autoadd_totp_spec(SseDeserializer deserializer);

  @protected
  BreachResult sse_decode_breach_result(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  DeviceDto sse_decode_device_dto(SseDeserializer deserializer);

  @protected
  EnrollmentDto sse_decode_enrollment_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Generated sse_decode_generated(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AuditEventDto> sse_decode_list_audit_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AuditFindingDto> sse_decode_list_audit_finding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BreachResult> sse_decode_list_breach_result(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceDto> sse_decode_list_device_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RemoteStatusDto? sse_decode_opt_box_autoadd_remote_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  ParsedTotp sse_decode_parsed_totp(SseDeserializer deserializer);

  @protected
  RemoteStatusDto sse_decode_remote_status_dto(SseDeserializer deserializer);

  @protected
  StrengthDto sse_decode_strength_dto(SseDeserializer deserializer);

  @protected
  SyncReportDto sse_decode_sync_report_dto(SseDeserializer deserializer);

  @protected
  TotpCodeDto sse_decode_totp_code_dto(SseDeserializer deserializer);

  @protected
  TotpSpec sse_decode_totp_spec(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer);

  @protected
  void sse_encode_audit_event_dto(AuditEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_audit_finding_dto(
    AuditFindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_status_dto(
    RemoteStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_totp_spec(
    TotpSpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_breach_result(BreachResult self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_device_dto(DeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_enrollment_dto(EnrollmentDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_generated(Generated self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_event_dto(
    List<AuditEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_audit_finding_dto(
    List<AuditFindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_breach_result(
    List<BreachResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_dto(
    List<DeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_status_dto(
    RemoteStatusDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_totp(ParsedTotp self, SseSerializer serializer);

  @protected
  void sse_encode_remote_status_dto(
    RemoteStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strength_dto(StrengthDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_report_dto(SyncReportDto self, SseSerializer serializer);

  @protected
  void sse_encode_totp_code_dto(TotpCodeDto self, SseSerializer serializer);

  @protected
  void sse_encode_totp_spec(TotpSpec self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
