// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `handle`, `listen`, `pair`, `pending`, `serve`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 启动（或重新启用）本地通道。配对请求通过 `sink` 推送给 Dart。重复调用只替换 sink。
Stream<PairingRequest> startBrowserBridge() =>
    RustLib.instance.api.crateApiBrowserStartBrowserBridge();

/// 关闭集成：通道保持监听但拒绝一切请求（监听线程无法安全中断，且重新启用时无需重建）。
Future<void> stopBrowserBridge() =>
    RustLib.instance.api.crateApiBrowserStopBrowserBridge();

/// Dart 弹窗的用户选择。
Future<void> respondPairing({
  required String clientId,
  required bool approved,
}) => RustLib.instance.api.crateApiBrowserRespondPairing(
  clientId: clientId,
  approved: approved,
);

Future<List<BrowserClientDto>> listBrowserClients() =>
    RustLib.instance.api.crateApiBrowserListBrowserClients();

Future<void> removeBrowserClient({required String id}) =>
    RustLib.instance.api.crateApiBrowserRemoveBrowserClient(id: id);

/// 在各 Chromium 系浏览器中登记 Native Messaging 宿主（宿主程序与主程序位于同一目录）。
/// 返回写入的清单路径。Windows 写 HKCU 注册表；macOS / Linux 写用户级清单目录。
Future<String> registerNativeHost() =>
    RustLib.instance.api.crateApiBrowserRegisterNativeHost();

class BrowserClientDto {
  final String id;
  final String name;
  final PlatformInt64 createdAt;
  final PlatformInt64 lastUsedAt;

  const BrowserClientDto({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.lastUsedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ createdAt.hashCode ^ lastUsedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BrowserClientDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          lastUsedAt == other.lastUsedAt;
}

class PairingRequest {
  final String clientId;

  /// 扩展自报的浏览器名（仅用于展示）
  final String name;

  /// 由配对密钥派生，用户须核对与扩展弹窗中显示的一致
  final String code;

  const PairingRequest({
    required this.clientId,
    required this.name,
    required this.code,
  });

  @override
  int get hashCode => clientId.hashCode ^ name.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingRequest &&
          runtimeType == other.runtimeType &&
          clientId == other.clientId &&
          name == other.name &&
          code == other.code;
}
