// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear`, `current_hash`, `set_sensitive`

/// 复制敏感文本。返回 false 表示当前平台不支持，调用方应降级。
bool clipboardCopySensitive({required String text}) =>
    RustLib.instance.api.crateApiClipboardClipboardCopySensitive(text: text);

/// 若剪贴板仍是我们写入的内容则清空，返回是否执行了清空。
bool clipboardClearIfUnchanged() =>
    RustLib.instance.api.crateApiClipboardClipboardClearIfUnchanged();
