// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'vault.dart';

Future<EnrollmentDto> prepareRegistration({
  required String serverUrl,
  required String email,
  required String password,
  required String deviceName,
}) => RustLib.instance.api.crateApiCloudAccountPrepareRegistration(
  serverUrl: serverUrl,
  email: email,
  password: password,
  deviceName: deviceName,
);

Future<EnrollmentDto?> completeRegistration({
  required String serverUrl,
  required String password,
  required String secretKey,
  required String deviceName,
}) => RustLib.instance.api.crateApiCloudAccountCompleteRegistration(
  serverUrl: serverUrl,
  password: password,
  secretKey: secretKey,
  deviceName: deviceName,
);

Future<EnrollmentDto?> pendingEnrollment() =>
    RustLib.instance.api.crateApiCloudAccountPendingEnrollment();

Future<String?> pendingOperation() =>
    RustLib.instance.api.crateApiCloudAccountPendingOperation();

Future<void> confirmEnrollment() =>
    RustLib.instance.api.crateApiCloudAccountConfirmEnrollment();

Future<void> reconnect({
  required String serverUrl,
  required String password,
  required String secretKey,
}) => RustLib.instance.api.crateApiCloudAccountReconnect(
  serverUrl: serverUrl,
  password: password,
  secretKey: secretKey,
);

Future<void> logout() => RustLib.instance.api.crateApiCloudAccountLogout();

Future<void> changePassword({
  required String current,
  required String secretKey,
  required String newPassword,
}) => RustLib.instance.api.crateApiCloudAccountChangePassword(
  current: current,
  secretKey: secretKey,
  newPassword: newPassword,
);

Future<EnrollmentDto> recover({
  required String serverUrl,
  required String email,
  required String recoveryCode,
  required String secretKey,
  required String newPassword,
  required String deviceName,
}) => RustLib.instance.api.crateApiCloudAccountRecover(
  serverUrl: serverUrl,
  email: email,
  recoveryCode: recoveryCode,
  secretKey: secretKey,
  newPassword: newPassword,
  deviceName: deviceName,
);
