// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> listConflicts({required bool includeHistory}) => RustLib
    .instance
    .api
    .crateApiConflictsListConflicts(includeHistory: includeHistory);

Future<String> getConflict({required String id}) =>
    RustLib.instance.api.crateApiConflictsGetConflict(id: id);

Future<String> refreshConflict({required String id}) =>
    RustLib.instance.api.crateApiConflictsRefreshConflict(id: id);

Future<void> resolveConflict({
  required String id,
  required String resolutionJson,
}) => RustLib.instance.api.crateApiConflictsResolveConflict(
  id: id,
  resolutionJson: resolutionJson,
);
