// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> newFeedbackId() =>
    RustLib.instance.api.crateApiFeedbackNewFeedbackId();

Future<String> submitFeedback({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiFeedbackSubmitFeedback(requestJson: requestJson);

Future<String> listFeedback({PlatformInt64? before, required int limit}) =>
    RustLib.instance.api.crateApiFeedbackListFeedback(
      before: before,
      limit: limit,
    );

Future<String> getFeedback({required String id}) =>
    RustLib.instance.api.crateApiFeedbackGetFeedback(id: id);
