// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化日志（重复调用无副作用）。`verbose` 为诊断模式，输出 debug 级别。
Future<void> initLogging({required String logDir, required bool verbose}) =>
    RustLib.instance.api.crateApiLoggingInitLogging(
      logDir: logDir,
      verbose: verbose,
    );

/// 供 Dart 侧把 UI 层事件写入同一日志（调用方负责不传入敏感信息）。
Future<void> logEvent({required String level, required String message}) =>
    RustLib.instance.api.crateApiLoggingLogEvent(
      level: level,
      message: message,
    );
