// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_to_window`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AffinityTargets`

/// 开关截图保护。返回是否至少有一个窗口被成功设置；`false` 表示当前平台不支持。
bool setProtection({required bool enabled}) =>
    RustLib.instance.api.crateApiScreenshotSetProtection(enabled: enabled);

/// 当前平台是否支持截图保护。界面据此决定开关是否可点，避免用户打开一个没有作用的选项。
bool isSupported() => RustLib.instance.api.crateApiScreenshotIsSupported();
