// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'vault.dart';

// These functions are ignored because they are not marked as `pub`: `profile_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<RemoteStatusDto?> remoteStatus() =>
    RustLib.instance.api.crateApiSyncRemoteStatus();

/// 仅调试构建可登记一个私网 HTTP 服务器，None 撤销例外。
Future<void> configureDevelopmentHttp({String? serverUrl}) => RustLib
    .instance
    .api
    .crateApiSyncConfigureDevelopmentHttp(serverUrl: serverUrl);

/// 测试服务器连通性。
Future<void> pingServer({required String serverUrl}) =>
    RustLib.instance.api.crateApiSyncPingServer(serverUrl: serverUrl);

/// 已有本地账户 → 注册到同步服务并完成首次同步。
Future<SyncReportDto> connectRegister({
  required String serverUrl,
  required String deviceName,
}) => RustLib.instance.api.crateApiSyncConnectRegister(
  serverUrl: serverUrl,
  deviceName: deviceName,
);

/// 新设备登录已有账户。返回 true 表示已完成加入；false 表示需要验证设备。
Future<bool> loginExisting({
  required String serverUrl,
  required String email,
  required String password,
  required String secretKey,
  required String deviceName,
}) => RustLib.instance.api.crateApiSyncLoginExisting(
  serverUrl: serverUrl,
  email: email,
  password: password,
  secretKey: secretKey,
  deviceName: deviceName,
);

Future<void> verifyNewDevice({required String code}) =>
    RustLib.instance.api.crateApiSyncVerifyNewDevice(code: code);

/// 轮询：是否已被其他设备批准（批准后自动完成加入）。
Future<bool> checkNewDeviceApproved() =>
    RustLib.instance.api.crateApiSyncCheckNewDeviceApproved();

Future<SyncReportDto> syncNow() => RustLib.instance.api.crateApiSyncSyncNow();

Future<void> reconnect({required String password, required String secretKey}) =>
    RustLib.instance.api.crateApiSyncReconnect(
      password: password,
      secretKey: secretKey,
    );

Future<void> disconnect() => RustLib.instance.api.crateApiSyncDisconnect();

Future<void> deleteRemoteAccount({
  required String password,
  required String secretKey,
}) => RustLib.instance.api.crateApiSyncDeleteRemoteAccount(
  password: password,
  secretKey: secretKey,
);

Future<List<DeviceDto>> listDevices() =>
    RustLib.instance.api.crateApiSyncListDevices();

Future<void> approveDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiSyncApproveDevice(deviceId: deviceId);

Future<void> revokeDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiSyncRevokeDevice(deviceId: deviceId);

Future<List<AuditEventDto>> auditEvents() =>
    RustLib.instance.api.crateApiSyncAuditEvents();

/// 所有设备丢失后，用 Recovery Kit 从云端恢复。
Future<EnrollmentDto> recoverFromServer({
  required String serverUrl,
  required String email,
  required String recoveryCode,
  required String secretKey,
  required String newPassword,
  required String deviceName,
}) => RustLib.instance.api.crateApiSyncRecoverFromServer(
  serverUrl: serverUrl,
  email: email,
  recoveryCode: recoveryCode,
  secretKey: secretKey,
  newPassword: newPassword,
  deviceName: deviceName,
);

/// 读取账户资料（§8.1）。**联网失败不报错**，回退到本机缓存并置 `online=false` ——
/// 账户总览在离线时也该有东西可显示，这正是本地优先的意思。
Future<AccountProfileDto> accountProfile() =>
    RustLib.instance.api.crateApiSyncAccountProfile();

/// 更新账户资料（§8.2）。需要联网；成功后服务端返回的值即为新值。
Future<AccountProfileDto> updateAccountProfile({
  required String nickname,
  required String avatar,
}) => RustLib.instance.api.crateApiSyncUpdateAccountProfile(
  nickname: nickname,
  avatar: avatar,
);

/// 补填邀请人邀请码（§9）。一次性绑定，绑定后不可更改；需要联网。
Future<AccountProfileDto> bindInvite({required String code}) =>
    RustLib.instance.api.crateApiSyncBindInvite(code: code);

/// 账户资料。`online` 表示本次是否成功从服务端刷新；失败时返回的是本机缓存。
class AccountProfileDto {
  final String nickname;
  final String avatar;
  final PlatformInt64 createdAt;

  /// 我的邀请码（§8.1 / §9）。旧服务端不返回时为空。
  final String inviteCode;
  final bool online;

  const AccountProfileDto({
    required this.nickname,
    required this.avatar,
    required this.createdAt,
    required this.inviteCode,
    required this.online,
  });

  @override
  int get hashCode =>
      nickname.hashCode ^
      avatar.hashCode ^
      createdAt.hashCode ^
      inviteCode.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountProfileDto &&
          runtimeType == other.runtimeType &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          createdAt == other.createdAt &&
          inviteCode == other.inviteCode &&
          online == other.online;
}

class AuditEventDto {
  final String event;
  final String? deviceId;
  final PlatformInt64 createdAt;

  const AuditEventDto({
    required this.event,
    this.deviceId,
    required this.createdAt,
  });

  @override
  int get hashCode => event.hashCode ^ deviceId.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEventDto &&
          runtimeType == other.runtimeType &&
          event == other.event &&
          deviceId == other.deviceId &&
          createdAt == other.createdAt;
}

class DeviceDto {
  final String id;
  final String name;
  final String platform;
  final bool approved;
  final bool current;
  final PlatformInt64 createdAt;
  final PlatformInt64? lastSeenAt;
  final bool revoked;

  const DeviceDto({
    required this.id,
    required this.name,
    required this.platform,
    required this.approved,
    required this.current,
    required this.createdAt,
    this.lastSeenAt,
    required this.revoked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      platform.hashCode ^
      approved.hashCode ^
      current.hashCode ^
      createdAt.hashCode ^
      lastSeenAt.hashCode ^
      revoked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          platform == other.platform &&
          approved == other.approved &&
          current == other.current &&
          createdAt == other.createdAt &&
          lastSeenAt == other.lastSeenAt &&
          revoked == other.revoked;
}

class RemoteStatusDto {
  final String serverUrl;
  final String deviceId;
  final String deviceName;
  final PlatformInt64? lastSyncAt;
  final BigInt pending;

  const RemoteStatusDto({
    required this.serverUrl,
    required this.deviceId,
    required this.deviceName,
    this.lastSyncAt,
    required this.pending,
  });

  @override
  int get hashCode =>
      serverUrl.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      lastSyncAt.hashCode ^
      pending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteStatusDto &&
          runtimeType == other.runtimeType &&
          serverUrl == other.serverUrl &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          lastSyncAt == other.lastSyncAt &&
          pending == other.pending;
}

class SyncReportDto {
  final int pulled;
  final int pushed;
  final int merged;
  final int conflicts;
  final bool credentialsUpdated;

  const SyncReportDto({
    required this.pulled,
    required this.pushed,
    required this.merged,
    required this.conflicts,
    required this.credentialsUpdated,
  });

  @override
  int get hashCode =>
      pulled.hashCode ^
      pushed.hashCode ^
      merged.hashCode ^
      conflicts.hashCode ^
      credentialsUpdated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReportDto &&
          runtimeType == other.runtimeType &&
          pulled == other.pulled &&
          pushed == other.pushed &&
          merged == other.merged &&
          conflicts == other.conflicts &&
          credentialsUpdated == other.credentialsUpdated;
}
