// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Generated generatePassword({
  required int length,
  required bool lowercase,
  required bool uppercase,
  required bool digits,
  required bool symbols,
  required bool excludeAmbiguous,
}) => RustLib.instance.api.crateApiToolsGeneratePassword(
  length: length,
  lowercase: lowercase,
  uppercase: uppercase,
  digits: digits,
  symbols: symbols,
  excludeAmbiguous: excludeAmbiguous,
);

Generated generatePassphrase({
  required int words,
  required String separator,
  required bool capitalize,
  required bool includeNumber,
}) => RustLib.instance.api.crateApiToolsGeneratePassphrase(
  words: words,
  separator: separator,
  capitalize: capitalize,
  includeNumber: includeNumber,
);

StrengthDto passwordStrength({
  required String password,
  required List<String> userInputs,
}) => RustLib.instance.api.crateApiToolsPasswordStrength(
  password: password,
  userInputs: userInputs,
);

TotpCodeDto totpCode({required TotpSpec spec, required BigInt unixTime}) =>
    RustLib.instance.api.crateApiToolsTotpCode(spec: spec, unixTime: unixTime);

/// 解析 otpauth:// 链接（扫码结果）或手输 Base32 密钥。
ParsedTotp parseTotp({required String text}) =>
    RustLib.instance.api.crateApiToolsParseTotp(text: text);

class Generated {
  final String value;
  final double entropyBits;

  const Generated({required this.value, required this.entropyBits});

  @override
  int get hashCode => value.hashCode ^ entropyBits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Generated &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          entropyBits == other.entropyBits;
}

class ParsedTotp {
  final TotpSpec spec;
  final String? issuer;
  final String? account;

  const ParsedTotp({required this.spec, this.issuer, this.account});

  @override
  int get hashCode => spec.hashCode ^ issuer.hashCode ^ account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedTotp &&
          runtimeType == other.runtimeType &&
          spec == other.spec &&
          issuer == other.issuer &&
          account == other.account;
}

class StrengthDto {
  final int score;
  final double guessesLog10;
  final String? warning;

  const StrengthDto({
    required this.score,
    required this.guessesLog10,
    this.warning,
  });

  @override
  int get hashCode => score.hashCode ^ guessesLog10.hashCode ^ warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrengthDto &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          guessesLog10 == other.guessesLog10 &&
          warning == other.warning;
}

class TotpCodeDto {
  final String code;
  final int remaining;
  final int period;

  const TotpCodeDto({
    required this.code,
    required this.remaining,
    required this.period,
  });

  @override
  int get hashCode => code.hashCode ^ remaining.hashCode ^ period.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TotpCodeDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          remaining == other.remaining &&
          period == other.period;
}

class TotpSpec {
  final String secret;
  final String alg;
  final int digits;
  final int period;

  const TotpSpec({
    required this.secret,
    required this.alg,
    required this.digits,
    required this.period,
  });

  @override
  int get hashCode =>
      secret.hashCode ^ alg.hashCode ^ digits.hashCode ^ period.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TotpSpec &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          alg == other.alg &&
          digits == other.digits &&
          period == other.period;
}
