// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `item_value`, `items_json`, `slot`, `with_vault`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 打开（不存在则创建）本地保险库文件。
Future<void> openVault({required String path}) =>
    RustLib.instance.api.crateApiVaultOpenVault(path: path);

Future<VaultStatus> status() => RustLib.instance.api.crateApiVaultStatus();

/// 创建本地账户（Argon2id m=64MiB,t=3,p=4，32 字节随机盐）。
Future<EnrollmentDto> createAccount({
  required String email,
  required String password,
}) => RustLib.instance.api.crateApiVaultCreateAccount(
  email: email,
  password: password,
);

Future<void> unlock({required String password, required String secretKey}) =>
    RustLib.instance.api.crateApiVaultUnlock(
      password: password,
      secretKey: secretKey,
    );

Future<void> unlockWithQuickKey({required List<int> key}) =>
    RustLib.instance.api.crateApiVaultUnlockWithQuickKey(key: key);

/// 返回的快速解锁密钥应立即写入系统钥匙串（受生物识别保护），Dart 侧不得另存。
Future<Uint8List> enableQuickUnlock() =>
    RustLib.instance.api.crateApiVaultEnableQuickUnlock();

Future<void> disableQuickUnlock() =>
    RustLib.instance.api.crateApiVaultDisableQuickUnlock();

Future<void> verifyMasterPassword({
  required String password,
  required String secretKey,
}) => RustLib.instance.api.crateApiVaultVerifyMasterPassword(
  password: password,
  secretKey: secretKey,
);

Future<void> lock() => RustLib.instance.api.crateApiVaultLock();

Future<AccountInfo> accountInfo() =>
    RustLib.instance.api.crateApiVaultAccountInfo();

Future<void> changePassword({
  required String current,
  required String secretKey,
  required String newPassword,
}) => RustLib.instance.api.crateApiVaultChangePassword(
  current: current,
  secretKey: secretKey,
  newPassword: newPassword,
);

Future<EnrollmentDto> recoverLocal({
  required String recoveryCode,
  required String secretKey,
  required String newPassword,
}) => RustLib.instance.api.crateApiVaultRecoverLocal(
  recoveryCode: recoveryCode,
  secretKey: secretKey,
  newPassword: newPassword,
);

/// 全部未删除条目（JSON 数组）。
Future<String> listItems() => RustLib.instance.api.crateApiVaultListItems();

Future<String> listTrash() => RustLib.instance.api.crateApiVaultListTrash();

Future<String> createItem({required String dataJson}) =>
    RustLib.instance.api.crateApiVaultCreateItem(dataJson: dataJson);

Future<String> updateItem({required String id, required String dataJson}) =>
    RustLib.instance.api.crateApiVaultUpdateItem(id: id, dataJson: dataJson);

Future<void> deleteItem({required String id}) =>
    RustLib.instance.api.crateApiVaultDeleteItem(id: id);

Future<void> restoreItem({required String id}) =>
    RustLib.instance.api.crateApiVaultRestoreItem(id: id);

/// 本地弱密码 / 重复密码审计。
Future<List<AuditFindingDto>> auditLocal() =>
    RustLib.instance.api.crateApiVaultAuditLocal();

/// 对指定条目做 HIBP 泄露检测（k-匿名：只发送 SHA-1 前 5 位），返回 (条目 ID, 泄露次数)。
Future<List<BreachResult>> checkBreaches({required List<String> itemIds}) =>
    RustLib.instance.api.crateApiVaultCheckBreaches(itemIds: itemIds);

/// 从其他密码管理器的导出文件导入（CSV / 1PIF，自动识别）。文件内容只在内存中解析后立即加密入库。
Future<ImportSummary> importItems({required String content}) =>
    RustLib.instance.api.crateApiVaultImportItems(content: content);

/// 对页面 URL 做防钓鱼匹配，返回按匹配质量排序的条目 ID。
Future<List<String>> matchItems({required String pageUrl}) =>
    RustLib.instance.api.crateApiVaultMatchItems(pageUrl: pageUrl);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiVaultGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiVaultSetSetting(key: key, value: value);

/// 清空本机保险库（注销本机 / 重置应用）。
Future<void> wipeLocal() => RustLib.instance.api.crateApiVaultWipeLocal();

class AccountInfo {
  final String accountId;
  final String email;
  final String kdfSummary;
  final BigInt pendingChanges;
  final BigInt itemCount;

  const AccountInfo({
    required this.accountId,
    required this.email,
    required this.kdfSummary,
    required this.pendingChanges,
    required this.itemCount,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      email.hashCode ^
      kdfSummary.hashCode ^
      pendingChanges.hashCode ^
      itemCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email &&
          kdfSummary == other.kdfSummary &&
          pendingChanges == other.pendingChanges &&
          itemCount == other.itemCount;
}

class AuditFindingDto {
  final String itemId;
  final bool weak;
  final int score;
  final int reusedWith;

  const AuditFindingDto({
    required this.itemId,
    required this.weak,
    required this.score,
    required this.reusedWith,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^ weak.hashCode ^ score.hashCode ^ reusedWith.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditFindingDto &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          weak == other.weak &&
          score == other.score &&
          reusedWith == other.reusedWith;
}

class BreachResult {
  final String itemId;
  final BigInt count;

  const BreachResult({required this.itemId, required this.count});

  @override
  int get hashCode => itemId.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreachResult &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          count == other.count;
}

class EnrollmentDto {
  final String accountId;
  final String email;
  final String secretKey;
  final String recoveryCode;

  const EnrollmentDto({
    required this.accountId,
    required this.email,
    required this.secretKey,
    required this.recoveryCode,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      email.hashCode ^
      secretKey.hashCode ^
      recoveryCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrollmentDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email &&
          secretKey == other.secretKey &&
          recoveryCode == other.recoveryCode;
}

class ImportSummary {
  /// 识别出的来源：chrome / firefox / bitwarden / lastpass / 1password / 1pif / csv
  final String format;
  final int added;
  final int duplicates;

  /// 格式不合法被拒绝的条目数 + 文件中无法转换的记录数
  final int skipped;

  const ImportSummary({
    required this.format,
    required this.added,
    required this.duplicates,
    required this.skipped,
  });

  @override
  int get hashCode =>
      format.hashCode ^ added.hashCode ^ duplicates.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportSummary &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          added == other.added &&
          duplicates == other.duplicates &&
          skipped == other.skipped;
}

class VaultStatus {
  final bool initialized;
  final bool unlocked;
  final String? accountId;
  final bool quickUnlockEnabled;
  final bool pendingLogin;

  const VaultStatus({
    required this.initialized,
    required this.unlocked,
    this.accountId,
    required this.quickUnlockEnabled,
    required this.pendingLogin,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^
      unlocked.hashCode ^
      accountId.hashCode ^
      quickUnlockEnabled.hashCode ^
      pendingLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          unlocked == other.unlocked &&
          accountId == other.accountId &&
          quickUnlockEnabled == other.quickUnlockEnabled &&
          pendingLogin == other.pendingLogin;
}
