// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `item_value`, `items_json`, `probe_environment`, `slot`, `with_vault`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// 打开（不存在则创建）本地保险库文件。
///
/// 同一进程内可能有多个 Flutter 引擎（Android 自动填充界面与主界面共用进程）：已打开同一文件时直接复用，
/// 不替换现有实例，因此主界面已解锁时自动填充无需再次解锁。
Future<void> openVault({required String path}) =>
    RustLib.instance.api.crateApiVaultOpenVault(path: path);

Future<VaultStatus> status() => RustLib.instance.api.crateApiVaultStatus();

/// 创建本地账户（Argon2id m=64MiB,t=3,p=4，32 字节随机盐）。
Future<EnrollmentDto> createAccount({
  required String email,
  required String password,
}) => RustLib.instance.api.crateApiVaultCreateAccount(
  email: email,
  password: password,
);

Future<void> unlock({required String password, required String secretKey}) =>
    RustLib.instance.api.crateApiVaultUnlock(
      password: password,
      secretKey: secretKey,
    );

Future<void> unlockWithQuickKey({required List<int> key}) =>
    RustLib.instance.api.crateApiVaultUnlockWithQuickKey(key: key);

/// 返回的快速解锁密钥应立即写入系统钥匙串（受生物识别保护），Dart 侧不得另存。
Future<Uint8List> enableQuickUnlock() =>
    RustLib.instance.api.crateApiVaultEnableQuickUnlock();

Future<void> disableQuickUnlock() =>
    RustLib.instance.api.crateApiVaultDisableQuickUnlock();

Future<void> verifyMasterPassword({
  required String password,
  required String secretKey,
}) => RustLib.instance.api.crateApiVaultVerifyMasterPassword(
  password: password,
  secretKey: secretKey,
);

/// 备份二次确认：把用户重输的 Secret Key 与本机保存的做逐字节比对（解析后 30 字节，常量时间）。
///
/// 大小写、分组连字符、空白与 I/L/O 的手抄差异被容忍，字节内容必须完全一致。成功时返回
/// 本机 Secret Key 的规范形态，供备份卡与展示使用。格式错误与内容不符返回同一个
/// `secret_key_mismatch`，不给出手抄位置信号。
Future<String> verifySecretKey({
  required String stored,
  required String candidate,
}) => RustLib.instance.api.crateApiVaultVerifySecretKey(
  stored: stored,
  candidate: candidate,
);

/// 恢复码规范化：本机不保存恢复码字节，只校验 Crockford Base32 格式并返回规范形态，
/// 供备份卡与恢复套件重新导出使用。内容是否属于当前账户由服务端在真正恢复时判定。
Future<String> canonicalRecoveryCode({required String candidate}) => RustLib
    .instance
    .api
    .crateApiVaultCanonicalRecoveryCode(candidate: candidate);

Future<void> lock() => RustLib.instance.api.crateApiVaultLock();

Future<AccountInfo> accountInfo() =>
    RustLib.instance.api.crateApiVaultAccountInfo();

Future<void> changePassword({
  required String current,
  required String secretKey,
  required String newPassword,
}) => RustLib.instance.api.crateApiVaultChangePassword(
  current: current,
  secretKey: secretKey,
  newPassword: newPassword,
);

Future<EnrollmentDto> recoverLocal({
  required String recoveryCode,
  required String secretKey,
  required String newPassword,
}) => RustLib.instance.api.crateApiVaultRecoverLocal(
  recoveryCode: recoveryCode,
  secretKey: secretKey,
  newPassword: newPassword,
);

/// 全部未删除条目（JSON 数组）。
Future<String> listItems() => RustLib.instance.api.crateApiVaultListItems();

Future<String> listTrash() => RustLib.instance.api.crateApiVaultListTrash();

Future<String> createItem({required String dataJson}) =>
    RustLib.instance.api.crateApiVaultCreateItem(dataJson: dataJson);

Future<String> updateItem({required String id, required String dataJson}) =>
    RustLib.instance.api.crateApiVaultUpdateItem(id: id, dataJson: dataJson);

Future<void> deleteItem({required String id}) =>
    RustLib.instance.api.crateApiVaultDeleteItem(id: id);

Future<void> restoreItem({required String id}) =>
    RustLib.instance.api.crateApiVaultRestoreItem(id: id);

/// 从回收站彻底删除条目（本机物理抹除，不可恢复）。要求该条目的删除已同步。
Future<void> purgeItem({required String id}) =>
    RustLib.instance.api.crateApiVaultPurgeItem(id: id);

/// 清空回收站：逐条抹除已同步条目，未同步的保留。返回 (已抹除, 保留)。
Future<EmptyTrashResult> emptyTrash() =>
    RustLib.instance.api.crateApiVaultEmptyTrash();

/// 本地弱密码 / 重复密码审计。
Future<List<AuditFindingDto>> auditLocal() =>
    RustLib.instance.api.crateApiVaultAuditLocal();

/// 标签与分类的批量管理（计划书 §3.6）。四个操作都返回受影响的条目数。
///
/// 全部走内核的 `update_item`，因此版本号与同步语义与手动编辑完全一致。
Future<int> taxonomyRenameTag({required String from, required String to}) =>
    RustLib.instance.api.crateApiVaultTaxonomyRenameTag(from: from, to: to);

Future<int> taxonomyDeleteTag({required String tag}) =>
    RustLib.instance.api.crateApiVaultTaxonomyDeleteTag(tag: tag);

/// 前缀改写：`工作` → `职业` 会连同 `工作/生产/服务器` 一起改。
Future<int> taxonomyRenameCategory({
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiVaultTaxonomyRenameCategory(
  from: from,
  to: to,
);

/// 清空分类（含子分类）的归属，不删条目。
Future<int> taxonomyClearCategory({required String path}) =>
    RustLib.instance.api.crateApiVaultTaxonomyClearCategory(path: path);

/// 分类树（JSON 数组，节点含 `name` / `path` / `direct` / `total` / `children`）。///
/// 分类是层级路径，树**从条目派生**而不是独立存储，因此聚合规则只在内核实现一处，
/// 界面直接消费；`total` 含后代汇总（计划书 §3.11）。
Future<String> categoryTree() =>
    RustLib.instance.api.crateApiVaultCategoryTree();

/// 对指定条目做 HIBP 泄露检测（k-匿名：只发送 SHA-1 前 5 位），返回 (条目 ID, 泄露次数)。
Future<List<BreachResult>> checkBreaches({required List<String> itemIds}) =>
    RustLib.instance.api.crateApiVaultCheckBreaches(itemIds: itemIds);

/// 运行一次安全体检，返回 `{ "report": …, "checklist": […] }`（计划书 §5.1 / §5.2）。
///
/// `breaches_json` 为 `{条目 id: 泄露次数}`；`breach_status` 取
/// `notRun` / `ok` / `unavailable` / `skipped`；`settings_json` 为安全设置快照。
/// 全部计算在内核完成（`vault_core::health`），界面只负责展示。
///
/// 报告与任务清单**一次算完一起返回**：分两次调用会各读一次设置，可能拿到不一致的快照
/// （例如刚改完自动锁定，报告用旧值、清单用新值）。
Future<String> healthCheckup({
  required String breachesJson,
  required String breachStatus,
  required String settingsJson,
}) => RustLib.instance.api.crateApiVaultHealthCheckup(
  breachesJson: breachesJson,
  breachStatus: breachStatus,
  settingsJson: settingsJson,
);

/// 导入预览（计划书 §3.7）：解析但不入库，交给界面核对与调整列映射。
///
/// `mapping_json` 为空时用自动识别结果；非空时按调用方给的列映射重新解析。
/// 条目以 JSON 数组返回，schema 由内核 `ItemData` 的 serde 唯一确定。
Future<String> importPreview({
  required String content,
  required String mappingJson,
}) => RustLib.instance.api.crateApiVaultImportPreview(
  content: content,
  mappingJson: mappingJson,
);

/// 按覆盖策略导入（计划书 §3.7）。`strategy` 取 `skip` / `overwrite` / `keepBoth`。
Future<ImportSummary> importItemsWith({
  required String content,
  required String mappingJson,
  required String strategy,
}) => RustLib.instance.api.crateApiVaultImportItemsWith(
  content: content,
  mappingJson: mappingJson,
  strategy: strategy,
);

/// 从其他密码管理器的导出文件导入（CSV / 1PIF，自动识别）。文件内容只在内存中解析后立即加密入库。
Future<ImportSummary> importItems({required String content}) =>
    RustLib.instance.api.crateApiVaultImportItems(content: content);

/// 导出加密备份包（`.wljbak`）字节流，由 Dart 侧写盘。
Future<Uint8List> exportBackup() =>
    RustLib.instance.api.crateApiVaultExportBackup();

/// 从加密备份包导入。返回 (新增, 跳过, 失败)。
Future<ImportSummary> importBackup({required List<int> data}) =>
    RustLib.instance.api.crateApiVaultImportBackup(data: data);

/// 导出为明文 CSV（迁移用，调用方须提示用户妥善保管）。
Future<String> exportCsv() => RustLib.instance.api.crateApiVaultExportCsv();

/// 对页面 URL 做防钓鱼匹配，返回按匹配质量排序的条目 ID。
Future<List<String>> matchItems({required String pageUrl}) =>
    RustLib.instance.api.crateApiVaultMatchItems(pageUrl: pageUrl);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiVaultGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiVaultSetSetting(key: key, value: value);

/// 清空本机保险库（注销本机 / 重置应用）。
Future<void> wipeLocal() => RustLib.instance.api.crateApiVaultWipeLocal();

class AccountInfo {
  final String accountId;
  final String email;
  final String kdfSummary;
  final BigInt pendingChanges;
  final BigInt itemCount;

  const AccountInfo({
    required this.accountId,
    required this.email,
    required this.kdfSummary,
    required this.pendingChanges,
    required this.itemCount,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      email.hashCode ^
      kdfSummary.hashCode ^
      pendingChanges.hashCode ^
      itemCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email &&
          kdfSummary == other.kdfSummary &&
          pendingChanges == other.pendingChanges &&
          itemCount == other.itemCount;
}

class AuditFindingDto {
  final String itemId;
  final bool weak;
  final int score;
  final int reusedWith;

  const AuditFindingDto({
    required this.itemId,
    required this.weak,
    required this.score,
    required this.reusedWith,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^ weak.hashCode ^ score.hashCode ^ reusedWith.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditFindingDto &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          weak == other.weak &&
          score == other.score &&
          reusedWith == other.reusedWith;
}

class BreachResult {
  final String itemId;
  final BigInt count;

  const BreachResult({required this.itemId, required this.count});

  @override
  int get hashCode => itemId.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreachResult &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          count == other.count;
}

class EmptyTrashResult {
  final int purged;
  final int kept;

  const EmptyTrashResult({required this.purged, required this.kept});

  @override
  int get hashCode => purged.hashCode ^ kept.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmptyTrashResult &&
          runtimeType == other.runtimeType &&
          purged == other.purged &&
          kept == other.kept;
}

class EnrollmentDto {
  final String accountId;
  final String email;
  final String secretKey;
  final String recoveryCode;

  const EnrollmentDto({
    required this.accountId,
    required this.email,
    required this.secretKey,
    required this.recoveryCode,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      email.hashCode ^
      secretKey.hashCode ^
      recoveryCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrollmentDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          email == other.email &&
          secretKey == other.secretKey &&
          recoveryCode == other.recoveryCode;
}

class ImportSummary {
  /// 识别出的来源：chrome / firefox / bitwarden / lastpass / 1password / 1pif / csv
  final String format;
  final int added;

  /// 按「覆盖」策略改写掉的现有条目数。
  final int updated;
  final int duplicates;

  /// 格式不合法被拒绝的条目数 + 文件中无法转换的记录数
  final int skipped;

  const ImportSummary({
    required this.format,
    required this.added,
    required this.updated,
    required this.duplicates,
    required this.skipped,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      added.hashCode ^
      updated.hashCode ^
      duplicates.hashCode ^
      skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportSummary &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          added == other.added &&
          updated == other.updated &&
          duplicates == other.duplicates &&
          skipped == other.skipped;
}

class VaultStatus {
  final bool initialized;
  final bool unlocked;
  final String? accountId;
  final bool quickUnlockEnabled;
  final bool pendingLogin;

  const VaultStatus({
    required this.initialized,
    required this.unlocked,
    this.accountId,
    required this.quickUnlockEnabled,
    required this.pendingLogin,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^
      unlocked.hashCode ^
      accountId.hashCode ^
      quickUnlockEnabled.hashCode ^
      pendingLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          unlocked == other.unlocked &&
          accountId == other.accountId &&
          quickUnlockEnabled == other.quickUnlockEnabled &&
          pendingLogin == other.pendingLogin;
}
